import React, { useEffect } from "react";
// import "../App.css";
import { useLocation, useNavigate } from "react-router-dom";
import { useSelector, useDispatch } from "react-redux";
import { Button, Form, Input, Alert } from "antd";
import { getLocalStorage } from "../helpers/frontendHelper";
function TwoFA({ setOpenTwoFa }) {
  function useQuery() {
    const { search } = useLocation();
    return React.useMemo(() => new URLSearchParams(search), [search]);
  }
  const twoFAData = getLocalStorage("twoFAData");
  const dispatch = useDispatch();
  const { error, error2fa, isLoading, sendLoading, success, isLoggedIn } =
    useSelector((state) => state.authenticationReducer);
  const onSubmitHandler = (values) => {
    console.log("submitted", values);
    dispatch({
      type: "VALIDATE_REQUEST",
      payload: {
        ...values,
        userId: twoFAData?.userId,
      },
    });
  };
  console.log("twoFAData", twoFAData);
  const [form] = Form.useForm();
  const [form1] = Form.useForm();
  const [form2] = Form.useForm();
  // const image = query.get("qrimg");
  const image = twoFAData?.data?.split("base64,")[1];
  // useEffect(() => {
  //   if (isLoggedIn) {
  //     navigate("/");
  //   }
  // }, [isLoggedIn]);
  const sendOTPHandler = (values) => {
    dispatch({
      type: "SEND_OTP_REQUEST",
      payload: values,
    });
  };
  const validateOTPHandler = (values) => {
    dispatch({
      type: "VALIDATE_OTP_REQUEST",
      payload: {
        ...values,
        userId: twoFAData?.userId,
      },
    });
  };

  return (
    <div className="google_aut h-100">
      <div className="row align-items-center justify-content-center">
        <div className="col-md-12 ">
          <div className="d-flex align-items-start  innerpills ">
            <div
              className="nav  nav-pills w-100"
              id="v-pills-tab"
              role="tablist"
              aria-orientation="vertical"
            >
              <a
                href=""
                className="nav-link active"
                id="v-pills-google2fa-tab"
                data-bs-toggle="pill"
                data-bs-target="#v-pills-google2fa"
                role="tab"
                aria-controls="v-pills-google2fa"
                aria-selected="true"
              >
                <i className="fab fa-google" /> Google 2fa Verification
              </a>
              <a
                href=""
                className="nav-link"
                id="v-pills-verifyemail-tab"
                data-bs-toggle="pill"
                data-bs-target="#v-pills-verifyemail"
                role="tab"
                aria-controls="v-pills-verifyemail"
                aria-selected="false"
              >
                {" "}
                <i className="fa fa-envelope" />
                Email Verification
              </a>
              <a
                href=""
                className="nav-link"
                id="v-pills-verifyphone-tab"
                data-bs-toggle="pill"
                data-bs-target="#v-pills-verifyphone"
                role="tab"
                aria-controls="v-pills-verifyphone"
                aria-selected="false"
              >
                {" "}
                <i className="fa fa-phone" />
                Phone Verification
              </a>
            </div>
          </div>
          <div className="tab-content" id="v-pills-tabContent">
            <div
              className="tab-pane fade show active"
              id="v-pills-google2fa"
              role="tabpanel"
              aria-labelledby="v-pills-google2fa-tab"
            >
              <div className="card card0 border-0 ">
                <div className=" text-center">
                  <h4>Enable Two-Factor Authentication</h4>
                  <p>
                    An administrator has required two-factor authentication for
                    one or more groups that you are a member of. To continue
                    working with the access that is granted to your account
                    enable this feature.
                  </p>
                  {/* <p>When you enable this feature, you need to enter your password and a code that is generated by a two-factor authentication to sign in.</p> */}
                  <div className="scan_code">
                    {image && (
                      <img
                        src={`data:image/png;base64,${image
                          .split(" ")
                          .join("+")}`}
                        alt=""
                        className="img-fluid "
                      />
                    )}
                  </div>
                  <div className="enter_code">
                    <h5>Enter 6-digit code from the app</h5>
                    {error2fa && (
                      <Alert type="error" message={error2fa}></Alert>
                    )}
                    <Form
                      form={form}
                      onFinish={onSubmitHandler}
                      initialValues={{ remember: true }}
                    >
                      <div className="inputs d-flex flex-row justify-content-center mt-2">
                        <Form.Item
                          name="Code"
                          className="w-50"
                          rules={[
                            {
                              required: "true",
                              message: "Please enter your code",
                            },
                            {
                              len: 6,
                              message: "Please enter 6 digit code",
                            },
                          ]}
                        >
                          <Input
                            className="m-2  text-center form-control rounded"
                            type="text"
                            id="first"
                            maxLength={6}
                          />
                        </Form.Item>
                      </div>
                      <div className="mt-4">
                        <Button
                          type="primary"
                          htmlType="submit"
                          loading={isLoading}
                          style={{ backgroundColor: "#1B9AA5" }}
                          className="btn btn- all_btn text-white"
                        >
                          Validate
                        </Button>
                        <button
                          type="button"
                          style={{ marginLeft: "5px" }}
                          onClick={(e) => {
                            e.preventDefault();
                            setOpenTwoFa(false);
                          }}
                          className="btn btn-danger text-white border-0"
                        >
                          Cancel
                        </button>
                      </div>
                    </Form>
                  </div>
                </div>
              </div>
            </div>
            <div
              className="tab-pane fade"
              id="v-pills-verifyemail"
              role="tabpanel"
              aria-labelledby="v-pills-verifyemail-tab"
            >
              <div className="card card0 border-0 ">
                <div className=" text-center">
                  <h4>Email Verification</h4>
                  <p>
                    An administrator has required two-factor authentication for
                    one or more groups that you are a member of. To continue
                    working with the access that is granted to your account
                    enable this feature.
                  </p>
                  <p>
                    When you enable this feature, you need to enter your
                    password and a code that is generated by a two-factor
                    authentication to sign in.
                  </p>
                  <div className="enter_code">
                    {/* <h5>Enter Email Address</h5> */}
                    <div className="bg-light p-3">
                      <Form
                        form={form1}
                        onFinish={sendOTPHandler}
                        initialValues={{
                          remember: true,
                          Email: twoFAData?.email,
                        }}
                        style={{
                          width: "100%",
                        }}
                      >
                        <div className="inputs  justify-content-center mt-2">
                          <div className="row align-items-flex-start">
                            <div className="col-md-8">
                              <Form.Item
                                name="Email"
                                rules={[
                                  {
                                    required: "true",
                                    message: "Please enter your email",
                                  },
                                  {
                                    type: "email",
                                    message: "Please enter valid email",
                                  },
                                ]}
                              >
                                <Input
                                  className="m-2 text-center form-control rounded w-100"
                                  type="text"
                                  placeholder="Enter your email address"
                                  id="first"
                                />
                              </Form.Item>
                            </div>
                            <div className="col-md-3 mt-2">
                              <Form.Item>
                                <Button
                                  type="primary"
                                  htmlType="submit"
                                  loading={sendLoading}
                                  style={{ backgroundColor: "#00205A" }}
                                  className="btn btn-sm all_btn text-white m-auto w-100"
                                >
                                  Send OTP
                                </Button>
                              </Form.Item>
                            </div>
                          </div>
                        </div>
                      </Form>
                      <p>
                        {success ? (
                          <Alert
                            message={success}
                            type="info"
                            style={{
                              fontSize: "13px",
                              margin: "15px 0",
                              textAlign: "center",
                            }}
                          ></Alert>
                        ) : (
                          error && (
                            <Alert
                              message={error}
                              type="error"
                              style={{
                                fontSize: "13px",
                                margin: "15px 0",
                                textAlign: "center",
                              }}
                            >
                              {error}
                            </Alert>
                          )
                        )}
                      </p>
                      <Form
                        form={form2}
                        id="otpForm"
                        onFinish={validateOTPHandler}
                      >
                        <Form.Item
                          name="Code"
                          rules={[
                            {
                              required: "true",
                              message: "Please enter your OTP",
                            },
                          ]}
                        >
                          <div className="inputs d-flex flex-row justify-content-center mt-2">
                            <Input
                              className="m-2 text-center form-control rounded"
                              type="text"
                              placeholder="Enter your OTP"
                              id="first"
                            />
                          </div>
                        </Form.Item>
                      </Form>
                    </div>
                    <div className="mt-4">
                      <Button
                        htmlFor="validateOTP"
                        htmlType="submit"
                        loading={isLoading}
                        form="otpForm"
                        style={{ backgroundColor: "#1B9AA5" }}
                        className="btn btn- all_btn text-white"
                      >
                        Validate
                      </Button>
                      <button
                        type="button"
                        style={{ marginLeft: "5px" }}
                        onClick={(e) => {
                          e.preventDefault();
                          setOpenTwoFa(false);
                        }}
                        className="btn btn-danger text-white border-0"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              className="tab-pane fade"
              id="v-pills-verifyphone"
              role="tabpanel"
              aria-labelledby="v-pills-verifyphone-tab"
            >
              <div className="card card0 border-0 ">
                <div className=" text-center">
                  <h4>Phone Verification Coming Soon</h4>
                  <p>
                    An administrator has required two-factor authentication for
                    one or more groups that you are a member of. To continue
                    working with the access that is granted to your account
                    enable this feature.
                  </p>
                  <p>
                    When you enable this feature, you need to enter your
                    password and a code that is generated by a two-factor
                    authentication to sign in.
                  </p>
                  {/* <div className="enter_code">
                        <div className="bg-light p-3">
                          <div className="row align-items-center">
                            <div className="col-md-9">
                              <input
                                className="m-2 text-center form-control rounded w-100"
                                type="text"
                                placeholder="Enter your Phone no."
                                id="first"
                              />
                            </div>
                            <div className="col-md-3">
                              <button
                                type="button"
                                className="btn btn-sm all_btn text-white m-auto w-100"
                              >
                                Send OTP
                              </button>
                            </div>
                          </div>
                          <div className="inputs d-flex flex-row justify-content-center mt-2">
                            <input
                              className="m-2 text-center form-control rounded"
                              type="text"
                              placeholder="Enter 6 digit code."
                              id="first"
                            />
                          </div>
                          <p>
                            <small>6 Disgit is sent to your phone.</small>
                          </p>
                        </div>
                        <div className="mt-4">
                          <button
                            type="button"
                            className="btn btn- all_btn text-white"
                          >
                            Validate
                          </button>
                          <button
                            type="button"
                            style={{ marginLeft: "5px" }}
                            onClick={(e) => {
                              e.preventDefault();
                              dispatch({ type: "LOGOUT" });

                              navigate("/login");
                            }}
                            className="btn btn-danger text-white border-0"
                          >
                            Cancel
                          </button>
                        </div>
                        <div className="form-check mt-3">
                          <input
                            className="form-check-input mt-2 catcheck"
                            type="checkbox"
                            defaultValue=""
                            id="defaultCheck1"
                          />
                          <label
                            className="form-check-label"
                            htmlFor="defaultCheck1"
                          >
                            Skip for 30 Days
                          </label>
                        </div>
                      </div> */}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default TwoFA;
