import React from "react";

function EmailVerification() {
  return (
    <div
      className="tab-pane fade"
      id="v-pills-verifyemail"
      role="tabpanel"
      aria-labelledby="v-pills-verifyemail-tab"
    >
      <div className="card card0 border-0 ">
        <div className=" text-center">
          <h4>Email Verification</h4>
          <p>
            When you enable this feature, you need to enter your password and a
            code that is generated by a two-factor authentication to sign in.
          </p>
          <div className="enter_code">
            {/* <h5>Enter Email Address</h5> */}
            <div className="bg-light p-3">
              <div className="inputs  justify-content-center mt-2">
                <div className="row align-items-center">
                  <div className="col-md-9">
                    <input
                      className="m-2 text-center form-control rounded w-100"
                      type="text"
                      placeholder="Enter your email address"
                      id="first"
                    />
                  </div>
                  <div className="col-md-3">
                    <button
                      type="button"
                      className="btn btn-sm all_btn text-white m-auto w-100"
                    >
                      Send OTP
                    </button>
                  </div>
                </div>
              </div>
              <div className="inputs d-flex flex-row justify-content-center mt-2">
                <input
                  className="m-2 text-center form-control rounded"
                  type="text"
                  placeholder="Enter your OTP"
                  id="first"
                />
              </div>
              <p>
                <small>OTP is sent to your email.</small>
              </p>
            </div>
            <div className="mt-4">
              <button type="button" className="btn btn- all_btn text-white">
                Validate
              </button>
              <button
                type="button"
                className="btn btn-danger text-white border-0"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default EmailVerification;
